### ISSUE TITLE
waifu.pics integration

### ISSUE THREAD

**Issue by rexor12** [rexor12/holobot#185]
Implement a new command that the users can use to query images from waifu.pics. To avoid spamming the API and being slow to respond, the images of a category should be queried in batches of 50 (configurable) and the results should be stored - since these are just URLs, it's cheaper than individual queries. Each user request should take one item from this list when available. When the list is exhausted, another batch request should be sent. A rate limit that spans all categories should be implemented to avoid spamming the API by many concurrent requests.

**Given** I am a user
**When** I invoke the `/react category: <waifu.pics category>` command
**Then** an embed with an image of the requested category is displayed alongside text describing the action

**Comment by tooruu** [comment]
suske
