### ISSUE TITLE
Stealing ractions

### ISSUE THREAD

**Issue by AdiReich** [rexor12/holobot#323]
### Summary

Whenever someone uses react command, there would be small chance for it to misfire and do something else.
For example react with other person or bot itself

### Why is this needed?

because it is a feature ppl would like to have on their server

### Checklist

- [X] I have made sure not to add ANY sensitive information (tokens, passwords, credentials, personal details, etc.).
- [X] I have searched the issue tracker and have made sure it is not a duplicate. If it is a follow up of another issue, I have specified it.

**Comment by rexor12** [comment]
Would these specifications fit your needs?

**Feature:** Altering a `/react` command usage
**Given** react misfire is enabled
**And** I am a user
**And** my next react invocation is predicted to misfire
**When** I invoke the command `/react action: hug target: Kriz`
**Then** the `action` and/or `target` are randomly chosen

**Feature:** Configure the probability of react misfires
**Given** I am the owner of the server
**When** I invoke the command `/react misfire set action_rate: N% target_rate: M%`
**And** I invoke the command `/react action: <any action> target: <any user>`
**Then** the chances of the `action` changing is `N%` and `target` changing is `M%`

This way server owners would be able to configure the rates or even disable the feature altogether on a per-server basis.

**Comment by AdiReich** [comment]
Yes, amazing idea

**Comment by tooruu** [comment]
Please, use appropriate names for your issues.
